print("Ingrese los siguientes datos:")
nombre = input("Nombre:")
rut = input("Rut:")
correo = input("Correo:")
telefono = input("Télefono:")

print("Nombre:" , nombre)
print(f"Rut: {nombre}" )
print("Correo: ",correo )
print("Télefono:",telefono )